version: '3'
services:
  front:
    container_name: front
    image: hassanhatem/front:latest
    restart: always
  nginx:
    container_name: nginx
    depends_on: # wait for the frontend to start
    - front
    image: hassanhatem/nginx:latest
    volumes:
      - /etc/letsencrypt/live/egymarketwatch.me/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/egymarketwatch.me/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
          - 80:80
    restart: always