version: '3'
services:
  front:
    container_name: front
    image: hassanhatem/front:latest
    restart: always
  nginx:
    container_name: nginx
    depends_on: # wait for the frontend to start
    - front
    image: hassanhatem/nginx:latest
    ports:
          - 80:80
    restart: always